---
- name: Add brew taps
  community.general.homebrew_tap:
    name: "{{item}}"
  with_items: "{{homebrew_taps}}"

- name: Install brew apps
  homebrew:
    name: "{{item}}"
    state: latest
  with_items: "{{homebrew_apps}}"

- name: Install brew casks
  homebrew_cask:
    name: "{{item}}"
    state: latest
  with_items: "{{homebrew_casks}}"
  ignore_errors: yes

- name: Install fzf completion
  shell: /opt/homebrew/opt/fzf/install
