---
- name: create vim directories
  file:
    path: "{{item}}"
    state: directory
  loop:
    - ~/.vim/autoload
    - ~/.vim/plugged
    - ~/.vim/spell
    - ~/.vim/tmp
    - ~/.vim/undodir

- name: symlink vimrc
  file:
    src: "~/.dotfiles/.vimrc"
    dest: "~/.vimrc"
    state: link

- name: install vim-plug
  command: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

- name: run plug install
  command: vim +PlugInstall +qall
